/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "cashier.payment": [
        {
            "name": "id",
            "required": true
        }
    ],
    "cashier.webhook": [],
    "horizon.stats.index": [],
    "horizon.workload.index": [],
    "horizon.masters.index": [],
    "horizon.monitoring.index": [],
    "horizon.monitoring.store": [],
    "horizon.monitoring-tag.paginate": [
        {
            "name": "tag",
            "required": true
        }
    ],
    "horizon.monitoring-tag.destroy": [
        {
            "name": "tag",
            "required": true
        }
    ],
    "horizon.jobs-metrics.index": [],
    "horizon.jobs-metrics.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.queues-metrics.index": [],
    "horizon.queues-metrics.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.jobs-batches.index": [],
    "horizon.jobs-batches.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.jobs-batches.retry": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.pending-jobs.index": [],
    "horizon.completed-jobs.index": [],
    "horizon.silenced-jobs.index": [],
    "horizon.failed-jobs.index": [],
    "horizon.failed-jobs.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.retry-jobs.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.jobs.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.index": [
        {
            "name": "view",
            "required": false
        }
    ],
    "home": [],
    "dashboard": [],
    "tontines.index": [],
    "tontines.store": [],
    "tontines.create": [],
    "tontines.show": [
        {
            "name": "tontine",
            "required": true,
            "binding": "id"
        }
    ],
    "tontines.edit": [
        {
            "name": "tontine",
            "required": true,
            "binding": "id"
        }
    ],
    "tontines.update": [
        {
            "name": "tontine",
            "required": true,
            "binding": "id"
        }
    ],
    "tontines.destroy": [
        {
            "name": "tontine",
            "required": true,
            "binding": "id"
        }
    ],
    "tontines.stats": [
        {
            "name": "tontine",
            "required": true,
            "binding": "id"
        }
    ],
    "tontines.dashboard": [
        {
            "name": "tontine",
            "required": true
        }
    ],
    "tontines.members.store": [
        {
            "name": "tontine",
            "required": true,
            "binding": "id"
        }
    ],
    "tontines.invites.store": [
        {
            "name": "tontine",
            "required": true,
            "binding": "id"
        }
    ],
    "tontines.contribute": [
        {
            "name": "tontine",
            "required": true,
            "binding": "id"
        }
    ],
    "tontine-members.index": [],
    "tontine-members.show": [
        {
            "name": "tontineMember",
            "required": true,
            "binding": "id"
        }
    ],
    "tontine-members.update": [
        {
            "name": "tontineMember",
            "required": true,
            "binding": "id"
        }
    ],
    "tontine-members.destroy": [
        {
            "name": "tontineMember",
            "required": true,
            "binding": "id"
        }
    ],
    "tontine-members.stats": [
        {
            "name": "tontineMember",
            "required": true,
            "binding": "id"
        }
    ],
    "tontine-members.contributions.store": [
        {
            "name": "tontineMember",
            "required": true,
            "binding": "id"
        }
    ],
    "tontine-contributions.index": [],
    "tontine-contributions.show": [
        {
            "name": "tontineContribution",
            "required": true,
            "binding": "id"
        }
    ],
    "tontine-contributions.update": [
        {
            "name": "tontineContribution",
            "required": true,
            "binding": "id"
        }
    ],
    "tontine-contributions.destroy": [
        {
            "name": "tontineContribution",
            "required": true,
            "binding": "id"
        }
    ],
    "tontine-contributions.mark-paid": [
        {
            "name": "tontineContribution",
            "required": true,
            "binding": "id"
        }
    ],
    "tontine-contributions.mark-late": [
        {
            "name": "tontineContribution",
            "required": true,
            "binding": "id"
        }
    ],
    "tontine-contributions.tontine": [
        {
            "name": "tontine",
            "required": true,
            "binding": "id"
        }
    ],
    "tontine-contributions.stats": [
        {
            "name": "tontine",
            "required": true,
            "binding": "id"
        }
    ],
    "tontine-invites.index": [],
    "tontine-invites.show": [
        {
            "name": "tontineInvite",
            "required": true,
            "binding": "id"
        }
    ],
    "tontine-invites.accept": [
        {
            "name": "tontineInvite",
            "required": true,
            "binding": "id"
        }
    ],
    "tontine-invites.decline": [
        {
            "name": "tontineInvite",
            "required": true,
            "binding": "id"
        }
    ],
    "tontine-invites.resend": [
        {
            "name": "tontineInvite",
            "required": true,
            "binding": "id"
        }
    ],
    "tontine-invites.destroy": [
        {
            "name": "tontineInvite",
            "required": true,
            "binding": "id"
        }
    ],
    "analytics": [],
    "contributions": [],
    "invitations": [],
    "stripe.checkout-success": [],
    "stripe.checkout-cancel": [],
    "users.index": [],
    "users.show": [
        {
            "name": "user",
            "required": true
        }
    ],
    "users.update": [
        {
            "name": "user",
            "required": true
        }
    ],
    "users.destroy": [
        {
            "name": "user",
            "required": true
        }
    ],
    "invite.token": [
        {
            "name": "token",
            "required": true
        }
    ],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "password.edit": [],
    "password.update": [],
    "appearance": [],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "logout": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
