import React, { createContext, useState, useContext } from 'react';

const translations = {
  en: {
    "dashboard.greeting": "Hi {name},",
    "dashboard.manage_money": "Let's manage your money",
    "dashboard.your_balance": "Your Balance",
    "dashboard.rewards": "Reward",
    "dashboard.add_money": "Add Money",
    "dashboard.quick_actions": "Quick Actions",
    "dashboard.send_money": "Send Money",
    "dashboard.receive_money": "Receive Money",
    "dashboard.deposit": "Deposit",
    "dashboard.withdraw": "Withdraw",
    "dashboard.transactions_overview": "Transactions Overview",
    "dashboard.financial_activity_this_week": "Your financial activity this week",
    "dashboard.latest_transactions": "Latest Transactions",
    "dashboard.no_transactions_yet": "No transactions yet.",
    "transaction.sent": "Sent",
    "transaction.received": "Received",
    "transaction.deposits": "Deposits",
    "transaction.withdrawals": "Withdrawals",
    "transaction.send_money": "Send Money",
    "transaction.receive_money": "Receive Money",
    "transaction.deposits_label": "Deposits",
    "transaction.withdrawals_label": "Withdrawals",
    "transaction_type.money_transfer": "Money Transfer",
    "transaction_type.money_received": "Money Received",
    "layout.sidebar.dashboard": "Dashboard",
    "layout.sidebar.wallet": "My Wallet",
    "layout.sidebar.send_money": "Send Money",
    "layout.sidebar.invest": "Invest",
    "layout.sidebar.fx_exchange": "FX Exchange",
    "layout.sidebar.crypto": "Crypto",
    "layout.sidebar.history": "History",
    "layout.sidebar.profile": "Profile",
    "layout.sidebar.sign_out": "Sign Out",
    "common.view_all": "View all",
    "common.bar": "Bar",
    "common.pie": "Pie",
    "common.amount": "Amount",
  },
  es: {
    "dashboard.greeting": "Hola {name},",
    "dashboard.manage_money": "Gestionemos tu dinero",
    "dashboard.your_balance": "Tu Saldo",
    "dashboard.rewards": "Recompensa",
    "dashboard.add_money": "Añadir Dinero",
    "dashboard.quick_actions": "Acciones Rápidas",
    "dashboard.send_money": "Enviar Dinero",
    "dashboard.receive_money": "Recibir Dinero",
    "dashboard.deposit": "Depositar",
    "dashboard.withdraw": "Retirar",
    "dashboard.transactions_overview": "Resumen de Transacciones",
    "dashboard.financial_activity_this_week": "Tu actividad financiera esta semana",
    "dashboard.latest_transactions": "Últimas Transacciones",
    "dashboard.no_transactions_yet": "Aún no hay transacciones.",
    "transaction.sent": "Enviado",
    "transaction.received": "Recibido",
    "transaction.deposits": "Depósitos",
    "transaction.withdrawals": "Retiros",
    "transaction.send_money": "Enviar Dinero",
    "transaction.receive_money": "Recibir Dinero",
    "transaction.deposits_label": "Depósitos",
    "transaction.withdrawals_label": "Retiros",
    "transaction_type.money_transfer": "Transferencia de Dinero",
    "transaction_type.money_received": "Dinero Recibido",
    "layout.sidebar.dashboard": "Tablero",
    "layout.sidebar.wallet": "Mi Billetera",
    "layout.sidebar.send_money": "Enviar Dinero",
    "layout.sidebar.invest": "Invertir",
    "layout.sidebar.fx_exchange": "Cambio de Divisas",
    "layout.sidebar.crypto": "Cripto",
    "layout.sidebar.history": "Historial",
    "layout.sidebar.profile": "Perfil",
    "layout.sidebar.sign_out": "Cerrar Sesión",
    "common.view_all": "Ver todo",
    "common.bar": "Barras",
    "common.pie": "Circular",
    "common.amount": "Monto",
  },
  fr: {
    "dashboard.greeting": "Bonjour {name},",
    "dashboard.manage_money": "Gérons votre argent",
    "dashboard.your_balance": "Votre Solde",
    "dashboard.rewards": "Récompense",
    "dashboard.add_money": "Ajouter de l'argent",
    "dashboard.quick_actions": "Actions Rapides",
    "dashboard.send_money": "Envoyer de l'argent",
    "dashboard.receive_money": "Recevoir de l'argent",
    "dashboard.deposit": "Dépôt",
    "dashboard.withdraw": "Retrait",
    "dashboard.transactions_overview": "Aperçu des transactions",
    "dashboard.financial_activity_this_week": "Votre activité financière cette semaine",
    "dashboard.latest_transactions": "Dernières Transactions",
    "dashboard.no_transactions_yet": "Aucune transaction pour le moment.",
    "transaction.sent": "Envoyé",
    "transaction.received": "Reçu",
    "transaction.deposits": "Dépôts",
    "transaction.withdrawals": "Retraits",
    "transaction.send_money": "Envoyer de l'argent",
    "transaction.receive_money": "Recevoir de l'argent",
    "transaction.deposits_label": "Dépôts",
    "transaction.withdrawals_label": "Retraits",
    "transaction_type.money_transfer": "Transfert d'argent",
    "transaction_type.money_received": "Argent Reçu",
    "layout.sidebar.dashboard": "Tableau de bord",
    "layout.sidebar.wallet": "Mon Portefeuille",
    "layout.sidebar.send_money": "Envoyer de l'argent",
    "layout.sidebar.invest": "Investir",
    "layout.sidebar.fx_exchange": "Change Devises",
    "layout.sidebar.crypto": "Crypto",
    "layout.sidebar.history": "Historique",
    "layout.sidebar.profile": "Profil",
    "layout.sidebar.sign_out": "Se Déconnecter",
    "common.view_all": "Voir tout",
    "common.bar": "Barres",
    "common.pie": "Circulaire",
    "common.amount": "Montant",
  },
  ar: {
    "dashboard.greeting": "مرحباً {name},",
    "dashboard.manage_money": "لندير أموالك",
    "dashboard.your_balance": "رصيدك",
    "dashboard.rewards": "مكافأة",
    "dashboard.add_money": "إضافة أموال",
    "dashboard.quick_actions": "إجراءات سريعة",
    "dashboard.send_money": "إرسال أموال",
    "dashboard.receive_money": "استلام أموال",
    "dashboard.deposit": "إيداع",
    "dashboard.withdraw": "سحب",
    "dashboard.transactions_overview": "نظرة عامة على المعاملات",
    "dashboard.financial_activity_this_week": "نشاطك المالي هذا الأسبوع",
    "dashboard.latest_transactions": "أحدث المعاملات",
    "dashboard.no_transactions_yet": "لا توجد معاملات بعد.",
    "transaction.sent": "مرسل",
    "transaction.received": "مستلم",
    "transaction.deposits": "إيداعات",
    "transaction.withdrawals": "سحوبات",
    "transaction.send_money": "إرسال أموال",
    "transaction.receive_money": "استلام أموال",
    "transaction.deposits_label": "إيداعات",
    "transaction.withdrawals_label": "سحوبات",
    "transaction_type.money_transfer": "تحويل أموال",
    "transaction_type.money_received": "أموال مستلمة",
    "layout.sidebar.dashboard": "لوحة القيادة",
    "layout.sidebar.wallet": "محفظتي",
    "layout.sidebar.send_money": "إرسال أموال",
    "layout.sidebar.invest": "استثمار",
    "layout.sidebar.fx_exchange": "صرف العملات",
    "layout.sidebar.crypto": "عملات مشفرة",
    "layout.sidebar.history": "السجل",
    "layout.sidebar.profile": "الملف الشخصي",
    "layout.sidebar.sign_out": "تسجيل الخروج",
    "common.view_all": "عرض الكل",
    "common.bar": "أعمدة",
    "common.pie": "دائري",
    "common.amount": "المبلغ",
  },
  zh: {
    "dashboard.greeting": "你好 {name},",
    "dashboard.manage_money": "让我们来管理您的资金",
    "dashboard.your_balance": "您的余额",
    "dashboard.rewards": "奖励",
    "dashboard.add_money": "充值",
    "dashboard.quick_actions": "快捷操作",
    "dashboard.send_money": "汇款",
    "dashboard.receive_money": "收款",
    "dashboard.deposit": "存款",
    "dashboard.withdraw": "提款",
    "dashboard.transactions_overview": "交易概览",
    "dashboard.financial_activity_this_week": "您本周的财务活动",
    "dashboard.latest_transactions": "最新交易",
    "dashboard.no_transactions_yet": "暂无交易。",
    "transaction.sent": "已发送",
    "transaction.received": "已接收",
    "transaction.deposits": "存款",
    "transaction.withdrawals": "提款",
    "transaction.send_money": "汇款",
    "transaction.receive_money": "收款",
    "transaction.deposits_label": "存款",
    "transaction.withdrawals_label": "提款",
    "transaction_type.money_transfer": "转账",
    "transaction_type.money_received": "收到款项",
    "layout.sidebar.dashboard": "仪表板",
    "layout.sidebar.wallet": "我的钱包",
    "layout.sidebar.send_money": "汇款",
    "layout.sidebar.invest": "投资",
    "layout.sidebar.fx_exchange": "外汇兑换",
    "layout.sidebar.crypto": "加密货币",
    "layout.sidebar.history": "历史记录",
    "layout.sidebar.profile": "个人资料",
    "layout.sidebar.sign_out": "登出",
    "common.view_all": "查看全部",
    "common.bar": "柱状图",
    "common.pie": "饼图",
    "common.amount": "金额",
  },
  pt: {
    "dashboard.greeting": "Olá {name},",
    "dashboard.manage_money": "Vamos gerenciar seu dinheiro",
    "dashboard.your_balance": "Seu Saldo",
    "dashboard.rewards": "Recompensa",
    "dashboard.add_money": "Adicionar Dinheiro",
    "dashboard.quick_actions": "Ações Rápidas",
    "dashboard.send_money": "Enviar Dinheiro",
    "dashboard.receive_money": "Receber Dinheiro",
    "dashboard.deposit": "Depósito",
    "dashboard.withdraw": "Sacar",
    "dashboard.transactions_overview": "Visão Geral das Transações",
    "dashboard.financial_activity_this_week": "Sua atividade financeira esta semana",
    "dashboard.latest_transactions": "Últimas Transações",
    "dashboard.no_transactions_yet": "Nenhuma transação ainda.",
    "transaction.sent": "Enviado",
    "transaction.received": "Recebido",
    "transaction.deposits": "Depósitos",
    "transaction.withdrawals": "Saques",
    "transaction.send_money": "Enviar Dinheiro",
    "transaction.receive_money": "Receber Dinheiro",
    "transaction.deposits_label": "Depósitos",
    "transaction.withdrawals_label": "Saques",
    "transaction_type.money_transfer": "Transferência de Dinheiro",
    "transaction_type.money_received": "Dinheiro Recebido",
    "layout.sidebar.dashboard": "Painel",
    "layout.sidebar.wallet": "Minha Carteira",
    "layout.sidebar.send_money": "Enviar Dinheiro",
    "layout.sidebar.invest": "Investir",
    "layout.sidebar.fx_exchange": "Câmbio",
    "layout.sidebar.crypto": "Cripto",
    "layout.sidebar.history": "Histórico",
    "layout.sidebar.profile": "Perfil",
    "layout.sidebar.sign_out": "Sair",
    "common.view_all": "Ver tudo",
    "common.bar": "Gráfico de Barras",
    "common.pie": "Gráfico de Pizza",
    "common.amount": "Valor",
  },
};


const LanguageContext = createContext();

export function LanguageProvider({ children }) {
    const [language, setLanguage] = useState('en');

    const changeLanguage = (lang) => {
        setLanguage(lang);
        if (lang === 'ar') {
            document.documentElement.dir = 'rtl';
        } else {
            document.documentElement.dir = 'ltr';
        }
    };

    const t = (key, params = {}) => {
        let translation = (translations[language] && translations[language][key]) || translations['en'][key] || key;
        Object.keys(params).forEach(param => {
            translation = translation.replace(`{${param}}`, params[param]);
        });
        return translation;
    };

    return (
        <LanguageContext.Provider value={{ language, changeLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useTranslation() {
    return useContext(LanguageContext);
}